version: '3.3'

services:
  db:
    image: mysql
    container_name: example-wordpress-mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - example

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: example-phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 300M
    networks:
      - example

  wordpress:
    depends_on:
      - db
    container_name: example-wordpress
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes:
      - ./public:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 'true'
    networks:
      - example
networks:
  example:
volumes:
  db_data:

